package com.example.k3s2_psk1lab.mybatis.model;

public class Athlete {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ATHLETE.ATHLETE_ID
     *
     * @mbg.generated Mon Apr 29 03:49:47 EEST 2024
     */
    private Long athleteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ATHLETE.NAME
     *
     * @mbg.generated Mon Apr 29 03:49:47 EEST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ATHLETE.SURNAME
     *
     * @mbg.generated Mon Apr 29 03:49:47 EEST 2024
     */
    private String surname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ATHLETE.TEAM_ID
     *
     * @mbg.generated Mon Apr 29 03:49:47 EEST 2024
     */
    private Long teamId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ATHLETE.ATHLETE_ID
     *
     * @return the value of PUBLIC.ATHLETE.ATHLETE_ID
     *
     * @mbg.generated Mon Apr 29 03:49:47 EEST 2024
     */
    public Long getAthleteId() {
        return athleteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ATHLETE.ATHLETE_ID
     *
     * @param athleteId the value for PUBLIC.ATHLETE.ATHLETE_ID
     *
     * @mbg.generated Mon Apr 29 03:49:47 EEST 2024
     */
    public void setAthleteId(Long athleteId) {
        this.athleteId = athleteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ATHLETE.NAME
     *
     * @return the value of PUBLIC.ATHLETE.NAME
     *
     * @mbg.generated Mon Apr 29 03:49:47 EEST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ATHLETE.NAME
     *
     * @param name the value for PUBLIC.ATHLETE.NAME
     *
     * @mbg.generated Mon Apr 29 03:49:47 EEST 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ATHLETE.SURNAME
     *
     * @return the value of PUBLIC.ATHLETE.SURNAME
     *
     * @mbg.generated Mon Apr 29 03:49:47 EEST 2024
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ATHLETE.SURNAME
     *
     * @param surname the value for PUBLIC.ATHLETE.SURNAME
     *
     * @mbg.generated Mon Apr 29 03:49:47 EEST 2024
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ATHLETE.TEAM_ID
     *
     * @return the value of PUBLIC.ATHLETE.TEAM_ID
     *
     * @mbg.generated Mon Apr 29 03:49:47 EEST 2024
     */
    public Long getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ATHLETE.TEAM_ID
     *
     * @param teamId the value for PUBLIC.ATHLETE.TEAM_ID
     *
     * @mbg.generated Mon Apr 29 03:49:47 EEST 2024
     */
    public void setTeamId(Long teamId) {
        this.teamId = teamId;
    }
}