package com.example.k3s2_psk1lab.mybatis.model;

public class Competition {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COMPETITION.ID
     *
     * @mbg.generated Mon Apr 29 03:49:47 EEST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COMPETITION.NAME
     *
     * @mbg.generated Mon Apr 29 03:49:47 EEST 2024
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COMPETITION.ID
     *
     * @return the value of PUBLIC.COMPETITION.ID
     *
     * @mbg.generated Mon Apr 29 03:49:47 EEST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COMPETITION.ID
     *
     * @param id the value for PUBLIC.COMPETITION.ID
     *
     * @mbg.generated Mon Apr 29 03:49:47 EEST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COMPETITION.NAME
     *
     * @return the value of PUBLIC.COMPETITION.NAME
     *
     * @mbg.generated Mon Apr 29 03:49:47 EEST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COMPETITION.NAME
     *
     * @param name the value for PUBLIC.COMPETITION.NAME
     *
     * @mbg.generated Mon Apr 29 03:49:47 EEST 2024
     */
    public void setName(String name) {
        this.name = name;
    }
}