package com.example.k3s2_psk1lab.mybatis.dao;

import com.example.k3s2_psk1lab.mybatis.model.Competition;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface CompetitionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPETITION
     *
     * @mbg.generated Mon Apr 29 03:49:47 EEST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPETITION
     *
     * @mbg.generated Mon Apr 29 03:49:47 EEST 2024
     */
    int insert(Competition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPETITION
     *
     * @mbg.generated Mon Apr 29 03:49:47 EEST 2024
     */
    Competition selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPETITION
     *
     * @mbg.generated Mon Apr 29 03:49:47 EEST 2024
     */
    List<Competition> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.COMPETITION
     *
     * @mbg.generated Mon Apr 29 03:49:47 EEST 2024
     */
    int updateByPrimaryKey(Competition record);
}